/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  ApiTokens: () => import('#controllers/api_tokens_controller'),
  Events: () => import('#controllers/events_controller'),
  Inboxes: () => import('#controllers/inboxes_controller'),
  Ingest: () => import('#controllers/ingest_controller'),
  Media: () => import('#controllers/media_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Share: () => import('#controllers/share_controller'),
  TwoFactorAuth: () => import('#controllers/two_factor_auth_controller'),
}
