/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = [
    'bodyJson',
    'bodyText',
    'contentType',
    'createdAt',
    'headers',
    'id',
    'inboxId',
    'ip',
    'method',
    'path',
    'query',
    'receivedAt',
    'sizeBytes',
  ] as const
  $columns = EventSchema.$columns
  @column()
  declare bodyJson: any | null
  @column()
  declare bodyText: string | null
  @column()
  declare contentType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare headers: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inboxId: string
  @column()
  declare ip: string | null
  @column()
  declare method: string
  @column()
  declare path: string
  @column()
  declare query: any
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare sizeBytes: number
}

export class InboxSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'defaultReplayUrl',
    'expiresAt',
    'id',
    'name',
    'updatedAt',
    'userId',
  ] as const
  $columns = InboxSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultReplayUrl: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class MediaSchema extends BaseModel {
  static $columns = [
    'blobPathname',
    'blobUrl',
    'collection',
    'conversions',
    'createdAt',
    'customProps',
    'disk',
    'fileName',
    'id',
    'mimeType',
    'modelId',
    'modelType',
    'orderColumn',
    'sizeBytes',
    'updatedAt',
  ] as const
  $columns = MediaSchema.$columns
  @column()
  declare blobPathname: string
  @column()
  declare blobUrl: string
  @column()
  declare collection: string
  @column()
  declare conversions: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customProps: any
  @column()
  declare disk: string
  @column()
  declare fileName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string
  @column()
  declare modelId: string
  @column()
  declare modelType: string
  @column()
  declare orderColumn: number
  @column()
  declare sizeBytes: bigint | number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OtpSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'expiresAt',
    'id',
    'type',
    'updatedAt',
    'usedAt',
    'userId',
    'verifiedToken',
  ] as const
  $columns = OtpSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare verifiedToken: string | null
}

export class ReplaySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'durationMs',
    'errorCode',
    'errorMessage',
    'eventId',
    'id',
    'responseBody',
    'responseHeaders',
    'statusCode',
    'targetUrl',
  ] as const
  $columns = ReplaySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare responseBody: string | null
  @column()
  declare responseHeaders: any | null
  @column()
  declare statusCode: number | null
  @column()
  declare targetUrl: string
}

export class ShareTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'expiresAt', 'id', 'token'] as const
  $columns = ShareTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class UserOauthAccountSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'id',
    'provider',
    'providerEmail',
    'providerUserId',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserOauthAccountSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare providerEmail: string | null
  @column()
  declare providerUserId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'id',
    'isTwoFactorEnabled',
    'password',
    'twoFactorRecoveryCodes',
    'twoFactorSecret',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isTwoFactorEnabled: boolean | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare twoFactorRecoveryCodes: string | null
  @column()
  declare twoFactorSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
